name: Mkdocs

permissions:
  contents: write

on:
  workflow_dispatch:

  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: mkdocs gh-deploy --force

      - run: git checkout gh-pages

      - name: Replace relative URLs
        run: |
          CI_PAGES_URL="https://$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY").github.io/$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")/"
          echo "$CI_PAGES_URL"
